# Generated by Django 4.2.5 on 2023-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HousePricePredictionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("total_sqf", models.IntegerField(blank=True, null=True)),
                ("bath", models.IntegerField(blank=True, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
